jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - uses: actions/cache@v3
      id: cache
      with:
        path: '**/node_modules' # node_modules 폴더를 캐싱합니다
        # package-lock.json 파일이 변경되었을 때 캐시될 수 있게 합니다
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        # cache hit이 발생하지 않았을 경우, restore-keys 에 있는 것을 꺼냅니다.
        # 단, npm ci 명령은 실행됩니다. 기존의 node_modules 캐시를 기반으로
        # 추가된 패키지만 설치할테니, 아예 처음부터 node_modules 폴더를 생성하는 것보다
        # 시간이 적게 걸릴 겁니다.
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm ci # 이게 무거운 작업입니다.
      # cache hit이 발생한 경우 (즉 package-lock.json이 변경되지 않은 경우)
      # npm ci 실행은 skip합니다.
      if: steps.cache.outputs.cache-hit != 'true'

    - run: npm run build-step2

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
